github:
  branch_name: main
  tooling_branch_name: main
conda_forge_output_validation: true
conda_build:
  pkg_format: '2'
build_platform:
    linux_ppc64le: linux_64  # PowerPC for Linux
    linux_aarch64: linux_64  # ARM for Linux
    osx_arm64: osx_64
